[2024-09-22T12:28:03.417+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-22T12:28:03.433+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.is_api_active manual__2024-09-22T12:28:01.863208+00:00 [queued]>
[2024-09-22T12:28:03.439+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.is_api_active manual__2024-09-22T12:28:01.863208+00:00 [queued]>
[2024-09-22T12:28:03.441+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-22T12:28:03.449+0000] {taskinstance.py:2888} INFO - Executing <Task(HttpSensor): is_api_active> on 2024-09-22 12:28:01.863208+00:00
[2024-09-22T12:28:03.453+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2452) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-22T12:28:03.456+0000] {standard_task_runner.py:72} INFO - Started process 2453 to run task
[2024-09-22T12:28:03.457+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'is_api_active', 'manual__2024-09-22T12:28:01.863208+00:00', '--job-id', '774', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpj29xlozo']
[2024-09-22T12:28:03.459+0000] {standard_task_runner.py:105} INFO - Job 774: Subtask is_api_active
[2024-09-22T12:28:03.529+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_dag.is_api_active manual__2024-09-22T12:28:01.863208+00:00 [running]> on host 6e2558f7c62d
[2024-09-22T12:28:03.595+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='is_api_active' AIRFLOW_CTX_EXECUTION_DATE='2024-09-22T12:28:01.863208+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-22T12:28:01.863208+00:00'
[2024-09-22T12:28:03.631+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-22T12:28:03.645+0000] {baseoperator.py:405} WARNING - HttpSensor.execute cannot be called outside TaskInstance!
[2024-09-22T12:28:03.651+0000] {http.py:137} INFO - Poking: generate_data/customers
[2024-09-22T12:28:03.695+0000] {base.py:84} INFO - Retrieving connection 'http_localhost'
[2024-09-22T12:28:03.736+0000] {base.py:336} INFO - Success criteria met. Exiting.
[2024-09-22T12:28:03.764+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-22T12:28:03.766+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=is_api_active, run_id=manual__2024-09-22T12:28:01.863208+00:00, execution_date=20240922T122801, start_date=20240922T122803, end_date=20240922T122803
[2024-09-22T12:28:03.807+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-22T12:28:03.855+0000] {taskinstance.py:3900} INFO - 3 downstream tasks scheduled from follow-on schedule check
[2024-09-22T12:28:03.858+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
