[2024-09-22T02:50:53.440+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-22T02:50:53.476+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_table_dag.create_order_table manual__2024-09-22T02:50:50.728044+00:00 [queued]>
[2024-09-22T02:50:53.489+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_table_dag.create_order_table manual__2024-09-22T02:50:50.728044+00:00 [queued]>
[2024-09-22T02:50:53.493+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-22T02:50:53.520+0000] {taskinstance.py:2888} INFO - Executing <Task(SQLExecuteQueryOperator): create_order_table> on 2024-09-22 02:50:50.728044+00:00
[2024-09-22T02:50:53.580+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=118) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-22T02:50:53.584+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'create_table_dag', 'create_order_table', 'manual__2024-09-22T02:50:50.728044+00:00', '--job-id', '273', '--raw', '--subdir', 'DAGS_FOLDER/create_table_dag.py', '--cfg-path', '/tmp/tmpnfl66dkw']
[2024-09-22T02:50:53.596+0000] {standard_task_runner.py:105} INFO - Job 273: Subtask create_order_table
[2024-09-22T02:50:53.599+0000] {standard_task_runner.py:72} INFO - Started process 123 to run task
[2024-09-22T02:50:53.735+0000] {task_command.py:467} INFO - Running <TaskInstance: create_table_dag.create_order_table manual__2024-09-22T02:50:50.728044+00:00 [running]> on host 6e2558f7c62d
[2024-09-22T02:50:53.914+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='create_table_dag' AIRFLOW_CTX_TASK_ID='create_order_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-22T02:50:50.728044+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-22T02:50:50.728044+00:00'
[2024-09-22T02:50:53.916+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-22T02:50:53.918+0000] {sql.py:266} INFO - Executing: drop table if exists ORDERS;

create table ORDERS (
    ord_id varchar PRIMARY KEY,
    cust_id varchar,
    prod_id varchar,
    count numeric
);
[2024-09-22T02:50:53.929+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-22T02:50:53.944+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-22T02:50:53.954+0000] {sql.py:509} INFO - Running statement: drop table if exists ORDERS;

create table ORDERS (
    ord_id varchar PRIMARY KEY,
    cust_id varchar,
    prod_id varchar,
    count numeric
);, parameters: None
[2024-09-22T02:50:53.978+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-22T02:50:53.979+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=create_table_dag, task_id=create_order_table, run_id=manual__2024-09-22T02:50:50.728044+00:00, execution_date=20240922T025050, start_date=20240922T025053, end_date=20240922T025053
[2024-09-22T02:50:54.045+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-22T02:50:54.083+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-22T02:50:54.086+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
