[2024-09-19T07:46:29.252+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-19T07:46:29.275+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.second_task scheduled__2024-09-17T00:00:00+00:00 [queued]>
[2024-09-19T07:46:29.284+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.second_task scheduled__2024-09-17T00:00:00+00:00 [queued]>
[2024-09-19T07:46:29.285+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-19T07:46:29.316+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): second_task> on 2024-09-17 00:00:00+00:00
[2024-09-19T07:46:29.327+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=52) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-19T07:46:29.333+0000] {standard_task_runner.py:72} INFO - Started process 58 to run task
[2024-09-19T07:46:29.331+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'second_task', 'scheduled__2024-09-17T00:00:00+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpmefka3ot']
[2024-09-19T07:46:29.337+0000] {standard_task_runner.py:105} INFO - Job 57: Subtask second_task
[2024-09-19T07:46:29.443+0000] {task_command.py:467} INFO - Running <TaskInstance: first_dag.second_task scheduled__2024-09-17T00:00:00+00:00 [running]> on host 7c2c6c4cfe77
[2024-09-19T07:46:29.547+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-17T00:00:00+00:00'
[2024-09-19T07:46:29.549+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-19T07:46:29.552+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-19T07:46:29.554+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey am task 2 and will be running after task 1']
[2024-09-19T07:46:29.566+0000] {subprocess.py:86} INFO - Output:
[2024-09-19T07:46:29.570+0000] {subprocess.py:93} INFO - hey am task 2 and will be running after task 1
[2024-09-19T07:46:29.571+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-19T07:46:29.596+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-19T07:46:29.597+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=second_task, run_id=scheduled__2024-09-17T00:00:00+00:00, execution_date=20240917T000000, start_date=20240919T074629, end_date=20240919T074629
[2024-09-19T07:46:29.608+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-19T07:46:29.623+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-19T07:46:29.627+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-09-19T10:45:43.846+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-19T10:45:43.889+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.second_task scheduled__2024-09-17T00:00:00+00:00 [queued]>
[2024-09-19T10:45:43.899+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.second_task scheduled__2024-09-17T00:00:00+00:00 [queued]>
[2024-09-19T10:45:43.900+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-19T10:45:43.911+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): second_task> on 2024-09-17 00:00:00+00:00
[2024-09-19T10:45:43.916+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=582) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-19T10:45:43.920+0000] {standard_task_runner.py:72} INFO - Started process 606 to run task
[2024-09-19T10:45:43.918+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'second_task', 'scheduled__2024-09-17T00:00:00+00:00', '--job-id', '176', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpu70r081d']
[2024-09-19T10:45:43.923+0000] {standard_task_runner.py:105} INFO - Job 176: Subtask second_task
[2024-09-19T10:45:43.982+0000] {task_command.py:467} INFO - Running <TaskInstance: first_dag.second_task scheduled__2024-09-17T00:00:00+00:00 [running]> on host 77aa4aabff6e
[2024-09-19T10:45:44.045+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='second_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-17T00:00:00+00:00'
[2024-09-19T10:45:44.048+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-19T10:45:44.051+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-19T10:45:44.053+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey am task 2 and will be running after task 1']
[2024-09-19T10:45:44.061+0000] {subprocess.py:86} INFO - Output:
[2024-09-19T10:45:44.064+0000] {subprocess.py:93} INFO - hey am task 2 and will be running after task 1
[2024-09-19T10:45:44.065+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-19T10:45:44.099+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-19T10:45:44.103+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=second_task, run_id=scheduled__2024-09-17T00:00:00+00:00, execution_date=20240917T000000, start_date=20240919T104543, end_date=20240919T104544
[2024-09-19T10:45:44.118+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-19T10:45:44.132+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-19T10:45:44.133+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
