[2024-09-22T12:52:23.454+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-22T12:52:23.468+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_table_dag.echo_task manual__2024-09-22T12:52:19.000256+00:00 [queued]>
[2024-09-22T12:52:23.474+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_table_dag.echo_task manual__2024-09-22T12:52:19.000256+00:00 [queued]>
[2024-09-22T12:52:23.475+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-22T12:52:23.483+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): echo_task> on 2024-09-22 12:52:19.000256+00:00
[2024-09-22T12:52:23.487+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2923) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-22T12:52:23.489+0000] {standard_task_runner.py:72} INFO - Started process 2924 to run task
[2024-09-22T12:52:23.489+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'create_table_dag', 'echo_task', 'manual__2024-09-22T12:52:19.000256+00:00', '--job-id', '827', '--raw', '--subdir', 'DAGS_FOLDER/create_table_dag.py', '--cfg-path', '/tmp/tmptttqj2xp']
[2024-09-22T12:52:23.491+0000] {standard_task_runner.py:105} INFO - Job 827: Subtask echo_task
[2024-09-22T12:52:23.530+0000] {task_command.py:467} INFO - Running <TaskInstance: create_table_dag.echo_task manual__2024-09-22T12:52:19.000256+00:00 [running]> on host 6e2558f7c62d
[2024-09-22T12:52:23.642+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='create_table_dag' AIRFLOW_CTX_TASK_ID='echo_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-22T12:52:19.000256+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-22T12:52:19.000256+00:00'
[2024-09-22T12:52:23.645+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-22T12:52:23.648+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-22T12:52:23.650+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo created table successfully']
[2024-09-22T12:52:23.656+0000] {subprocess.py:86} INFO - Output:
[2024-09-22T12:52:23.659+0000] {subprocess.py:93} INFO - created table successfully
[2024-09-22T12:52:23.660+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-22T12:52:23.682+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-22T12:52:23.683+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=create_table_dag, task_id=echo_task, run_id=manual__2024-09-22T12:52:19.000256+00:00, execution_date=20240922T125219, start_date=20240922T125223, end_date=20240922T125223
[2024-09-22T12:52:23.712+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-22T12:52:23.731+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-22T12:52:23.734+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
