[2024-09-22T13:05:37.151+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-22T13:05:37.174+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_table_dag.create_order_table manual__2024-09-22T13:05:34.942796+00:00 [queued]>
[2024-09-22T13:05:37.184+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_table_dag.create_order_table manual__2024-09-22T13:05:34.942796+00:00 [queued]>
[2024-09-22T13:05:37.185+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-09-22T13:05:37.198+0000] {taskinstance.py:2888} INFO - Executing <Task(SQLExecuteQueryOperator): create_order_table> on 2024-09-22 13:05:34.942796+00:00
[2024-09-22T13:05:37.207+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3293) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-22T13:05:37.210+0000] {standard_task_runner.py:72} INFO - Started process 3297 to run task
[2024-09-22T13:05:37.207+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'create_table_dag', 'create_order_table', 'manual__2024-09-22T13:05:34.942796+00:00', '--job-id', '894', '--raw', '--subdir', 'DAGS_FOLDER/create_table_dag.py', '--cfg-path', '/tmp/tmpz8g0ho2b']
[2024-09-22T13:05:37.215+0000] {standard_task_runner.py:105} INFO - Job 894: Subtask create_order_table
[2024-09-22T13:05:37.356+0000] {task_command.py:467} INFO - Running <TaskInstance: create_table_dag.create_order_table manual__2024-09-22T13:05:34.942796+00:00 [running]> on host 6e2558f7c62d
[2024-09-22T13:05:37.727+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='create_table_dag' AIRFLOW_CTX_TASK_ID='create_order_table' AIRFLOW_CTX_EXECUTION_DATE='2024-09-22T13:05:34.942796+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-22T13:05:34.942796+00:00'
[2024-09-22T13:05:37.737+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-22T13:05:37.743+0000] {sql.py:266} INFO - Executing: drop table if exists ORDERS;

create table ORDERS (
    ord_id varchar PRIMARY KEY,
    cust_id varchar,
    prod_id varchar,
    count smallint
);
[2024-09-22T13:05:37.783+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-22T13:05:37.812+0000] {base.py:84} INFO - Retrieving connection 'postgres_localhost'
[2024-09-22T13:05:37.833+0000] {sql.py:509} INFO - Running statement: drop table if exists ORDERS;

create table ORDERS (
    ord_id varchar PRIMARY KEY,
    cust_id varchar,
    prod_id varchar,
    count smallint
);, parameters: None
[2024-09-22T13:05:37.874+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-22T13:05:37.875+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=create_table_dag, task_id=create_order_table, run_id=manual__2024-09-22T13:05:34.942796+00:00, execution_date=20240922T130534, start_date=20240922T130537, end_date=20240922T130537
[2024-09-22T13:05:37.903+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-22T13:05:37.979+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-22T13:05:37.986+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
