[2024-09-17T19:00:18.890+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-17T19:00:18.899+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.third_task manual__2024-09-17T19:00:16.471880+00:00 [queued]>
[2024-09-17T19:00:18.904+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.third_task manual__2024-09-17T19:00:16.471880+00:00 [queued]>
[2024-09-17T19:00:18.905+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-17T19:00:18.911+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): third_task> on 2024-09-17 19:00:16.471880+00:00
[2024-09-17T19:00:18.915+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=409) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-17T19:00:18.916+0000] {standard_task_runner.py:72} INFO - Started process 413 to run task
[2024-09-17T19:00:18.916+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'third_task', 'manual__2024-09-17T19:00:16.471880+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpoye1hko3']
[2024-09-17T19:00:18.917+0000] {standard_task_runner.py:105} INFO - Job 48: Subtask third_task
[2024-09-17T19:00:18.943+0000] {task_command.py:467} INFO - Running <TaskInstance: first_dag.third_task manual__2024-09-17T19:00:16.471880+00:00 [running]> on host 7c2c6c4cfe77
[2024-09-17T19:00:19.001+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-17T19:00:16.471880+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-17T19:00:16.471880+00:00'
[2024-09-17T19:00:19.003+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-17T19:00:19.006+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-17T19:00:19.007+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo this is task 3 and i will run after task 1']
[2024-09-17T19:00:19.012+0000] {subprocess.py:86} INFO - Output:
[2024-09-17T19:00:19.013+0000] {subprocess.py:93} INFO - this is task 3 and i will run after task 1
[2024-09-17T19:00:19.014+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-17T19:00:19.026+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-17T19:00:19.028+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=third_task, run_id=manual__2024-09-17T19:00:16.471880+00:00, execution_date=20240917T190016, start_date=20240917T190018, end_date=20240917T190019
[2024-09-17T19:00:19.057+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-17T19:00:19.066+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-17T19:00:19.067+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
