[2024-09-21T18:28:29.730+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-21T18:28:29.744+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: create_table_dag.echo_task scheduled__2024-09-20T00:00:00+00:00 [queued]>
[2024-09-21T18:28:29.750+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: create_table_dag.echo_task scheduled__2024-09-20T00:00:00+00:00 [queued]>
[2024-09-21T18:28:29.751+0000] {taskinstance.py:2865} INFO - Starting attempt 4 of 5
[2024-09-21T18:28:29.759+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): echo_task> on 2024-09-20 00:00:00+00:00
[2024-09-21T18:28:29.765+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=455) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-21T18:28:29.767+0000] {standard_task_runner.py:72} INFO - Started process 456 to run task
[2024-09-21T18:28:29.768+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'create_table_dag', 'echo_task', 'scheduled__2024-09-20T00:00:00+00:00', '--job-id', '241', '--raw', '--subdir', 'DAGS_FOLDER/create_table_dag.py', '--cfg-path', '/tmp/tmp6dne6e65']
[2024-09-21T18:28:29.769+0000] {standard_task_runner.py:105} INFO - Job 241: Subtask echo_task
[2024-09-21T18:28:29.818+0000] {task_command.py:467} INFO - Running <TaskInstance: create_table_dag.echo_task scheduled__2024-09-20T00:00:00+00:00 [running]> on host 6e2558f7c62d
[2024-09-21T18:28:29.875+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='create_table_dag' AIRFLOW_CTX_TASK_ID='echo_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-20T00:00:00+00:00'
[2024-09-21T18:28:29.876+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-21T18:28:29.878+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-21T18:28:29.880+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo created table successfully']
[2024-09-21T18:28:29.885+0000] {subprocess.py:86} INFO - Output:
[2024-09-21T18:28:29.887+0000] {subprocess.py:93} INFO - created table successfully
[2024-09-21T18:28:29.888+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-21T18:28:29.907+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-21T18:28:29.908+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=create_table_dag, task_id=echo_task, run_id=scheduled__2024-09-20T00:00:00+00:00, execution_date=20240920T000000, start_date=20240921T182829, end_date=20240921T182829
[2024-09-21T18:28:29.949+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-21T18:28:29.961+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-21T18:28:29.963+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
