[2024-09-19T10:45:40.847+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-19T10:45:40.984+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.third_task scheduled__2024-09-14T00:00:00+00:00 [queued]>
[2024-09-19T10:45:41.060+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.third_task scheduled__2024-09-14T00:00:00+00:00 [queued]>
[2024-09-19T10:45:41.062+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-09-19T10:45:41.185+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): third_task> on 2024-09-14 00:00:00+00:00
[2024-09-19T10:45:41.243+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'third_task', 'scheduled__2024-09-14T00:00:00+00:00', '--job-id', '171', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpk7ik6uk8']
[2024-09-19T10:45:41.251+0000] {standard_task_runner.py:105} INFO - Job 171: Subtask third_task
[2024-09-19T10:45:41.239+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=562) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-19T10:45:41.306+0000] {standard_task_runner.py:72} INFO - Started process 586 to run task
[2024-09-19T10:45:41.450+0000] {task_command.py:467} INFO - Running <TaskInstance: first_dag.third_task scheduled__2024-09-14T00:00:00+00:00 [running]> on host 77aa4aabff6e
[2024-09-19T10:45:41.847+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-14T00:00:00+00:00'
[2024-09-19T10:45:41.851+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-19T10:45:41.883+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-19T10:45:41.885+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo this is task 3 and i will run after task 1']
[2024-09-19T10:45:41.906+0000] {subprocess.py:86} INFO - Output:
[2024-09-19T10:45:41.915+0000] {subprocess.py:93} INFO - this is task 3 and i will run after task 1
[2024-09-19T10:45:41.919+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-19T10:45:42.146+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-19T10:45:42.162+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=third_task, run_id=scheduled__2024-09-14T00:00:00+00:00, execution_date=20240914T000000, start_date=20240919T104540, end_date=20240919T104542
[2024-09-19T10:45:42.298+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-19T10:45:42.462+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-19T10:45:42.486+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
